### ISSUE TITLE
Device name

### ISSUE THREAD

**Issue by Kolplays** [jeantichoc/pyvizio-easy#1]
Paired with the tv just fine, but can't seem to give it any commands.  Seems my device name is not what i think it is or something else. I just cant find what I am doing wrong.

python3 pyvizio-easy.py Family_Room_TV vol_up
Traceback (most recent call last):
  File "/home/files/pyvizio-easy/pyvizio-easy.py", line 187, in <module>
    execute_command(args.device_name, args.command, *args.args)
  File "/home/files/pyvizio-easy/pyvizio-easy.py", line 103, in execute_command
    vizio = get_vizio_device(device_name)
  File "/home/files/pyvizio-easy/pyvizio-easy.py", line 92, in get_vizio_device
    device_id, device_ip, auth_token, device_type = load_device_info(device_name)
  File "/home/files/pyvizio-easy/pyvizio-easy.py", line 35, in load_device_info
    device_info = pairing_info[device_name]
KeyError: 'Family_Room_TV'

**Comment by jeanbottein** [comment]
Hello !
can you show me the content of pyvizio-easy.json without the token please ?

**Comment by Kolplays** [comment]
{"Family Room TV": {"id": "king-Z97X-SLI-pyvizio-0-9855797", "auth_token": "Zqjmbqarpa", "type": "tv", "ip": "103.247.31.143"}}

**Comment by jeanbottein** [comment]
That's what I thought, the script registered your tv as Family Room TV not Family_Room_TV.

Try this command instead:
python3 pyvizio-easy.py "Family Room TV" vol_up

**Comment by Kolplays** [comment]
ya, mb I had tried different variations, i posted the wrong one, but its still the same, issue
.  python3 pyvizio-easy.py Family_Room_TV vol_up
Traceback (most recent call last):
  File "/home/file/pyvizio-easy/pyvizio-easy.py", line 187, in <module>
    execute_command(args.device_name, args.command, *args.args)
  File "/home/file/pyvizio-easy/pyvizio-easy.py", line 103, in execute_command
    vizio = get_vizio_device(device_name)
  File "/home/file/pyvizio-easy/pyvizio-easy.py", line 92, in get_vizio_device
    device_id, device_ip, auth_token, device_type = load_device_info(device_name)
  File "/home/file/pyvizio-easy/pyvizio-easy.py", line 35, in load_device_info
    device_info = pairing_info[device_name]
KeyError: 'Family_Room_TV'

**Comment by jeanbottein** [comment]
No with quotes
I'll try to replicate on my side otherwise, but for sur the _ are not generated in my code

**Comment by Kolplays** [comment]
Ok, got it to work.  Changing the device name from Family Room TV to FamilyR on the tv it self solved it.  Something to do with the spaces in the device name I'm guessing.
